

services:
  web:
    build: .
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: asyl
      POSTGRES_PASSWORD: 20061960
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
